[default.extend-words]
# Julia-specific functions
indexin = "indexin"
findfirst = "findfirst"
findlast = "findlast"
eachindex = "eachindex"
setp = "setp"
getp = "getp"
setu = "setu"
getu = "getu"

# Mathematical/scientific terms
jacobian = "jacobian"
hessian = "hessian" 
eigenvalue = "eigenvalue"
eigenvector = "eigenvector"
discretization = "discretization"
linearization = "linearization"
parameterized = "parameterized"
discretized = "discretized"
vectorized = "vectorized"

# Common variable patterns in Julia/SciML
ists = "ists"
ispcs = "ispcs"
osys = "osys"
rsys = "rsys"
usys = "usys"
fsys = "fsys"
eqs = "eqs"
rhs = "rhs"
lhs = "lhs"
ode = "ode"
pde = "pde"
sde = "sde"
dde = "dde"
bvp = "bvp"
ivp = "ivp"

# Common abbreviations
tol = "tol"
rtol = "rtol"
atol = "atol"
idx = "idx"
jdx = "jdx"
prev = "prev"
curr = "curr"
init = "init"
tmp = "tmp"
vec = "vec"
arr = "arr"
dt = "dt"
du = "du"
dx = "dx"
dy = "dy"
dz = "dz"

# Algorithm/type suffixes
alg = "alg"
prob = "prob"
sol = "sol"
cb = "cb"
opts = "opts"
args = "args"
kwargs = "kwargs"

# Scientific abbreviations
ND = "ND"
nd = "nd"
MTK = "MTK"
ODE = "ODE"
PDE = "PDE"
SDE = "SDE"

# MethodOfLines-specific terms
dorder = "dorder"  # Derivative order (mathematical term used throughout MOL)
dorders = "dorders"  # Plural of derivative order
upwind = "upwind"  # Upwinding scheme (numerical methods term)
downwind = "downwind"  # Downwinding scheme (numerical methods term)
upwinding = "upwinding"  # Process of upwinding
downwinding = "downwinding"  # Process of downwinding
discretized = "discretized"  # Past tense of discretize
discretization = "discretization"  # Process of discretizing
stencil = "stencil"  # Finite difference stencil
stencils = "stencils"  # Plural of stencil
gridpoint = "gridpoint"  # Point on computational grid
gridpoints = "gridpoints"  # Plural of gridpoint
ivs = "ivs"  # Independent variables (common abbreviation)
bcs = "bcs"  # Boundary conditions (common abbreviation)
pdesys = "pdesys"  # PDE system (variable name pattern)
ics = "ics"  # Initial conditions (common abbreviation)
discretizers = "discretizers"  # Objects that discretize
discretizer = "discretizer"  # Object that discretizes
Strat = "Strat"  # Strategy (type parameter abbreviation)
