steps:
  - label: ":pipeline:"
    plugins:
      - staticfloat/cryptic#v2:
          signed_pipelines:
            - pipeline: .buildkite/pipeline.yml
              signature_file: .buildkite/pipeline.yml.signature
    command: "true"
    agents:
      queue: "juliaecosystem"
