pages = [
    "MethodOfLines.jl: Automated Finite Difference for Phyiscs-Informed Learning" => "index.md",
    "Tutorials" => [
        "tutorials/brusselator.md",
        "tutorials/heat.md",
        "tutorials/params.md",
        "tutorials/heatss.md",
        "tutorials/sispde.md",
        "tutorials/icbc_sampled.md",
    ],
    "MOLFiniteDifference" => "MOLFiniteDifference.md",
    "Grid and Solution Retrieval" => "get_grid.md",
    "Boundary Conditions" => "boundary_conditions.md",
    "Non-Uniform Rectilinear Grids" => "nonuniform.md",
    "Curvilinear Grids" => "curvilinear_grids.md",
    "How it Works" => "howitworks.md",
    "Notes for Developers: Implement a Scheme" => "devnotes.md",
    "Generated Examples" => ["generated/bruss_code.md", "generated/bruss_ode_eqs.md"],
    # "Tutorial: Burgers" => "tutorials/burgers.md",
    # "Tutorial: 1D Linear Diffusion" => "tutorials/1d_linear_diffusion.md",
    # "Tutorial: 1D Non-Linear Diffusion" => "tutorials/1d_nonlinear_diffusion.md",
    # "Tutorial: 2D Diffusion" => "tutorials/2d_diffusion.md",
    # "Tutorial: 1D Linear Convection" => "tutorials/1d_linear_convection.md",
    # "Tutorial: 1D Higher Order" => "tutorials/1d_higher_order.md",
    # "Tutorial: Stationary Nonlinear Problems" => "tutorials/stationary_nonlinear_problems.md",
    # "Tutorial: 1D Partial DAE" => "tutorials/1d_partial_DAE.md",

]
